export enum PollResponseType {
    RATING_TO_FIVE = 'RATING_TO_FIVE',
    SHORT_ANSWER = 'SHORT_ANSWER',
    PROFESSOR_RATING = 'PROFESSOR_RATING',
    SHORT_NUMBER_ANSWER = 'SHORT_NUMBER_ANSWER',
    YES_NO_DESCRIPTION_IN_NO_ANSWER = 'YES_NO_DESCRIPTION_IN_NO_ANSWER'
}
